name: CI

on:
  push:
    branches: [ main, update-workshop ]
  pull_request:
    branches: [ main ]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Set up Python environment and run server tests
      run: ./scripts/run-server-tests.sh

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Set up Python environment and dependencies
      run: ./scripts/setup-environment.sh
    
    - name: Install Playwright Browsers
      working-directory: ./client
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: ./scripts/run-e2e-tests.sh
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: client/playwright-report/
        retention-days: 30
